# Generated by Django 4.2.6 on 2024-10-04 11:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("HEP_CREATE", "HEP create"),
                            ("HEP_UPDATE", "HEP update"),
                            ("AUTHOR_CREATE", "Author create"),
                            ("AUTHOR_UPDATE", "Author update"),
                        ],
                        default="HEP_CREATE",
                        max_length=30,
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("approval", "Waiting for approva"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="running",
                        max_length=30,
                    ),
                ),
                ("_created_at", models.DateTimeField(auto_now_add=True)),
                ("_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuthorWorkflowTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=32)),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("author_create_curation", "Author create curation"),
                            ("author_create_user", "Author create user"),
                            ("author_update_curation", "Author update curation"),
                        ],
                        default="author_create_curation",
                        max_length=30,
                    ),
                ),
                ("_created_at", models.DateTimeField(auto_now_add=True)),
                ("_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="authors.authorworkflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("accept", "author_create_approved_dag"),
                            ("reject", "author_create_rejected_dag"),
                            ("accept_curate", "author_create_approved_dag"),
                        ],
                        max_length=30,
                    ),
                ),
                ("_created_at", models.DateTimeField(auto_now_add=True)),
                ("_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="email",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="authors.authorworkflow",
                    ),
                ),
            ],
        ),
    ]
