# Generated by Django 4.2.6 on 2024-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("approval", "Waiting for approval"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="running",
                max_length=30,
            ),
        ),
    ]
