# Generated by Django 4.2.6 on 2024-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0002_alter_authorworkflow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("approval", "Waiting for approval"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="authorworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("HEP_CREATE", "HEP create"),
                    ("HEP_UPDATE", "HEP update"),
                    ("AUTHOR_CREATE", "Author create"),
                    ("AUTHOR_UPDATE", "Author update"),
                    ("DATA_CREATE", "Data create"),
                    ("DATA_UPDATE", "Data update"),
                ],
                default="HEP_CREATE",
                max_length=30,
            ),
        ),
    ]
