# Generated by Django 4.2.6 on 2025-06-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0003_alter_authorworkflow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("AUTHOR_CREATE", "Author create"),
                    ("AUTHOR_UPDATE", "Author update"),
                ],
                default="AUTHOR_CREATE",
                max_length=30,
            ),
        ),
    ]
