# Generated by Django 5.2.17 on 2026-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_authorworkflow_workflow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordecision',
            name='action',
            field=models.CharField(choices=[('accept', 'await_author_check_approval'), ('accept_curate', 'await_author_check_approval'), ('reject', 'await_author_check_approval')], max_length=30),
        ),
    ]
