# Generated by Django 4.2.6 on 2026-01-28 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authors", "0004_alter_authorworkflow_workflow_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authordecision",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="email",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
    ]
