# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

[pytest]
pep8maxlinelength = 88
pep8ignore = tests ALL
addopts = --pep8 --doctest-glob="*.rst" --doctest-modules --cov=inspirehep --cov-report=term-missing --ignore=setup.py -p no:warnings
testpaths = tests inspirehep
