name: Lint

on:
  workflow_call:
    inputs:
      ref:
        description: The reference to build
        type: string
        required: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: black
        uses: psf/black@stable
        with:
          options: "--verbose"

      - name: run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "flake8"
