name: Push main

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  backoffice:
    uses: ./.github/workflows/push-main-backoffice.yml
  workflows:
    uses: ./.github/workflows/push-main-workflows.yml
  success:
    name: All jobs passed
    runs-on: ubuntu-latest
    needs: [backoffice, workflows]
    steps:
        - name: All jobs passed
          run: echo "All jobs passed"
