name: Push main

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.ref }}
  test:
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
