name: Tests

on:
  workflow_call:
    inputs:
      ref:
        description: The reference to build
        type: string
        required: true
    outputs:
      image-id:
        description: The ID of image that has been built
        value: ${{ jobs.build.outputs.image-id }}

defaults:
  run:
    shell: bash

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ inputs.ref }}
      image: cern-sis/inspire/workflows
      context: ./workflows
      dockerfile: ./workflows/Dockerfile
    secrets: inherit
  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Current directory
        run: echo $(pwd)

      - name: Test
        env:
          AIRFLOW__CORE__EXECUTOR: CeleryExecutor
          AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
          AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres-airflow/airflow
          AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
          AIRFLOW__CORE__FERNET_KEY: ""
          AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
          AIRFLOW__CORE__LOAD_EXAMPLES: "false"
          AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
        run: >
          docker run
          --network=host
          -v "$(pwd)"/tests:/opt/airflow/tests
          -v "$(pwd)"/requirements-test.txt:/opt/airflow/requirements-test.txt
          -v "$(pwd)"/data:/opt/airflow/data
          registry.cern.ch/cern-sis/inspire/workflows@${{ needs.build.outputs.image-id }}
          bash -c "pip install -r requirements-test.txt && airflow db init && pytest /opt/airflow/tests"
