# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

FROM python:3.10

WORKDIR /opt/inspire

ENTRYPOINT ["poetry", "run", "inspirehep"]
CMD ["shell"]

ENV PYTHONBUFFERED=0 \
    PATH="/root/.local/bin:${PATH}" \
    POETRY_VIRTUALENVS_CREATE=false


RUN apt update && apt install poppler-utils -y

ARG POETRY_VERSION
ENV POETRY_VERSION="${POETRY_VERSION:-1.7.1}"
RUN curl -sSL https://install.python-poetry.org \
  | python3 - --git https://github.com/python-poetry/poetry.git#{$POETRY_VERSION} \
 && poetry --version

COPY poetry.lock pyproject.toml ./
RUN poetry install --no-root

COPY gunicorn_config.py ./
COPY inspirehep inspirehep/
COPY tests tests/
COPY scripts scripts/
COPY data data/

ARG VERSION
ENV VERSION="${VERSION}"

RUN poetry install
