# Generated by Django 4.2.6 on 2023-10-16 09:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkflowData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowMeta",
            fields=[
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="workflows.workflowdata",
                    ),
                ),
                ("core", models.BooleanField()),
                ("is_update", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStatus",
            fields=[
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="workflows.workflowdata",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREPROCESSING", "Preprocessing"),
                            ("APPROVAL", "Approval"),
                            ("POSTPROCESSING", "Postprocessing"),
                        ],
                        default="PREPROCESSING",
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
