# Generated by Django 4.2.6 on 2023-12-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0004_workflow_workflow_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("author_create_curation", "Author create curation"),
                    ("author_create_user", "Author create user"),
                ],
                default="author_create_curation",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("approval", "Waiting for approval"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="running",
                max_length=30,
            ),
        ),
    ]
