# Generated by Django 4.2.6 on 2024-08-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0009_decision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="workflows.workflow",
            ),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="workflow_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="workflows.workflow",
            ),
        ),
    ]
