name: Move to QA column

on:
  pull_request:
    types:
      - closed



jobs:
  move_to_qa:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    steps:
      - name: Echo PR number
        run: echo "PR number is ${{ github.event.number }}"
