#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""add journal_literature table"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils.types.uuid import UUIDType

# revision identifiers, used by Alembic.
revision = "0d1cf7c4501e"
down_revision = "35ba3d715114"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_literature",
        sa.Column("journal_uuid", UUIDType(), nullable=False),
        sa.Column("literature_uuid", UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["journal_uuid"],
            ["records_metadata.id"],
            name="fk_journal_literature_experiment_uuid",
        ),
        sa.ForeignKeyConstraint(
            ["literature_uuid"],
            ["records_metadata.id"],
            name="fk_journal_literature_literature_uuid",
        ),
        sa.PrimaryKeyConstraint(
            "journal_uuid", "literature_uuid", name=op.f("pk_journal_literature")
        ),
    )
    op.create_index(
        "ix_journal_experiment_journal_uuid",
        "journal_literature",
        ["journal_uuid"],
        unique=False,
    )
    op.create_index(
        "ix_journal_literature_literature_uuid",
        "journal_literature",
        ["literature_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_journal_literature_literature_uuid", table_name="journal_literature"
    )
    op.drop_index("ix_journal_experiment_journal_uuid", table_name="journal_literature")
    op.drop_table("journal_literature")
    # ### end Alembic commands ###
