#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Data collection citations"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "503b34c08b0b"
down_revision = "3fd6471bb960"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_literature",
        sa.Column("data_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "literature_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["data_uuid"], ["records_metadata.id"], name="fk_data_literature_data_uuid"
        ),
        sa.ForeignKeyConstraint(
            ["literature_uuid"],
            ["records_metadata.id"],
            name="fk_data_literature_literature_uuid",
        ),
        sa.PrimaryKeyConstraint(
            "data_uuid", "literature_uuid", name=op.f("pk_data_literature")
        ),
    )
    op.create_index(
        "ix_data_literature_data_uuid", "data_literature", ["data_uuid"], unique=False
    )
    op.create_index(
        "ix_data_literature_literature_uuid",
        "data_literature",
        ["literature_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_data_literature_literature_uuid", table_name="data_literature")
    op.drop_index("ix_data_literature_data_uuid", table_name="data_literature")
    op.drop_table("data_literature")
    # ### end Alembic commands ###
