#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add citation type to citation table"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "63a6686e24c4"
down_revision = "b0cdab232269"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records_citations",
        sa.Column(
            "citation_type",
            sa.Enum("citation", "self_citation", name="enum_citation_type"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("records_citations", "citation_type")
    # ### end Alembic commands ###
