#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""remove pid_provider index from pidstore"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "788a3a61a635"
down_revision = "dc1ae5abe9d6"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_pid_provider", table_name="pidstore_pid")
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_pid_provider",
        "pidstore_pid",
        ["object_uuid", "pid_provider"],
        unique=False,
    )
    # ### end Alembic commands ###
