#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""add index to pid_value in pidstore"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b0cdab232269"
down_revision = "f563233434cd"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_pidstore_pid_pid_value",
        "pidstore_pid",
        ["pid_value"],
        unique=False,
        postgresql_where=sa.sql.text("pid_provider = 'recid'"),
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_pidstore_pid_pid_value", table_name="pidstore_pid")
    # ### end Alembic commands ###
