#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""init oai"""

from alembic import op
from invenio_oaiserver.models import OAISet

# revision identifiers, used by Alembic.
revision = "c9f31d2a189d"
down_revision = "afe5f484abcc"
branch_labels = ()
depends_on = "e655021de0de"

SPEC_CDS = "ForCDS"
SPEC_CERN_ARXIV = "CERN:arXiv"


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        OAISet.__table__,
        [
            {"name": "CDS", "spec": SPEC_CDS, "description": "OAI set for CDS."},
            {
                "name": "CERN arXiv",
                "spec": SPEC_CERN_ARXIV,
                "description": "OAI set for CERN arXiv.",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DELETE FROM {OAISet.__table__.name} WHERE spec='{SPEC_CDS}';")
    op.execute(f"DELETE FROM {OAISet.__table__.name} WHERE spec='{SPEC_CERN_ARXIV}';")
    # ### end Alembic commands ###
