#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""add primary key to StudentsAdvisors table"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17cf574eb8b'
down_revision = '0ae62076ae0c'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_advisors', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students_advisors', 'id')
    # ### end Alembic commands ###
