# Generated by Django 4.2.6 on 2025-06-26 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HepWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField()),
                ("_created_at", models.DateTimeField(auto_now_add=True)),
                ("_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("HEP_CREATE", "HEP create"),
                            ("HEP_UPDATE", "HEP update"),
                        ],
                        default="HEP_CREATE",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("approval", "Waiting for approval"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="processing",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HepWorkflowTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=32)),
                ("_created_at", models.DateTimeField(auto_now_add=True)),
                ("_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("hep_create_curation", "HEP create curation"),
                            ("hep_update_curation", "HEP update curation"),
                        ],
                        default="hep_create_curation",
                        max_length=30,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="hep.hepworkflow",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HepDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created_at", models.DateTimeField(auto_now_add=True)),
                ("_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("accept", "hep_create_approved_dag"),
                            ("reject", "hep_create_rejected_dag"),
                            ("accept_curate", "hep_create_approved_dag"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="email",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="hep.hepworkflow",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
