# Generated by Django 4.2.6 on 2025-08-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hepdecision",
            name="value",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="hepdecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("match", "match"),
                    ("fuzzy_match", "fuzzy_match"),
                    ("approval", "approval"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hepworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("approval", "Waiting for approval"),
                    ("blocked", "Blocked"),
                    ("matching", "Matching"),
                    ("fuzzy_matching", "Fuzzy matching"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
    ]
