# Generated by Django 4.2.6 on 2025-09-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0002_hepdecision_value_alter_hepdecision_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hepworkflow",
            name="journal_coverage",
            field=models.CharField(
                blank=True,
                choices=[("full", "Full"), ("partial", "Partial")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hepdecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("exact_match", "await_decision_exact_match"),
                    ("fuzzy_match", "fuzzy_match"),
                    ("approval", "approval"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hepdecision",
            name="value",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
