# Generated by Django 4.2.6 on 2025-10-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0003_hepworkflow_journal_coverage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("approval", "Waiting for approval"),
                    ("blocked", "Blocked"),
                    ("fuzzy_matching", "Fuzzy matching"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
    ]
