# Generated by Django 4.2.6 on 2025-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0005_alter_hepworkflow_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="hepworkflow",
            name="merge_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
