# Generated by Django 4.2.6 on 2025-11-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0006_hepworkflow_merge_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="hepworkflow",
            name="matches",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
