# Generated by Django 4.2.6 on 2025-11-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0007_hepworkflow_matches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepdecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("exact_match", "await_decision_exact_match"),
                    ("fuzzy_match", "fuzzy_match"),
                    ("approval", "approval"),
                    ("core_selection", "core_selection"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hepworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("approval", "Waiting for approval"),
                    ("blocked", "Blocked"),
                    ("fuzzy_matching", "Fuzzy matching"),
                    ("core_selection", "Core Selection"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
    ]
