# Generated by Django 4.2.6 on 2025-11-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0008_alter_hepdecision_action_alter_hepworkflow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepdecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("exact_match", "await_decision_exact_match"),
                    ("fuzzy_match", "fuzzy_match"),
                    ("approval", "approval"),
                    ("hep_accept", "await_decision_approval"),
                    ("hep_accept_core", "await_decision_approval"),
                    ("hep_reject", "await_decision_approval"),
                    ("core_selection", "core_selection"),
                ],
                max_length=30,
            ),
        ),
    ]
