# Generated by Django 4.2.6 on 2025-11-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0010_alter_hepdecision_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("approval", "Waiting for approval"),
                    ("approval_core_selection", "Waiting for CORE selection approval"),
                    ("approval_fuzzy_matching", "Waiting for matching approval"),
                    ("approval_merge", "Waiting for merging conflicts"),
                    ("error", "Error"),
                    ("error_multiple_exact_matches", "Multiple exact matches"),
                    ("error_validation", "Validation error"),
                    ("running", "Running"),
                    ("blocked", "Blocked"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
    ]
