# Generated by Django 4.2.6 on 2026-01-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0017_alter_hepdecision_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepworkflowticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("hep_create_curation", "HEP create curation"),
                    ("hep_create_curation_core", "HEP create curation core"),
                    ("hep_update_curation", "HEP update curation"),
                    ("hep_submission", "HEP submission"),
                ],
                default="hep_create_curation",
                max_length=30,
            ),
        ),
    ]
