# Generated by Django 4.2.6 on 2026-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0018_alter_hepworkflowticket_ticket_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepworkflowticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("hep_create_curation", "HEP create curation"),
                    ("hep_create_curation_core", "HEP create curation core"),
                    (
                        "hep_create_publisher_curation_core",
                        "HEP create publisher curation",
                    ),
                    ("hep_update_curation", "HEP update curation"),
                    ("hep_submission", "HEP submission"),
                ],
                default="hep_create_curation",
                max_length=50,
            ),
        ),
    ]
