# Generated by Django 4.2.6 on 2026-01-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0019_alter_hepworkflowticket_ticket_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hepworkflow",
            name="form_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
