# Generated by Django 4.2.6 on 2026-01-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0020_hepworkflow_form_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("HEP_CREATE", "HEP create"),
                    ("HEP_SUBMISSION", "HEP submission"),
                    ("HEP_UPDATE", "HEP update"),
                ],
                default="HEP_CREATE",
                max_length=30,
            ),
        ),
    ]
