# Generated by Django 4.2.6 on 2026-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0020_hepworkflow_form_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="hepworkflow",
            name="blocked_by",
            field=models.ManyToManyField(
                blank=True, related_name="blocks", to="hep.hepworkflow"
            ),
        ),
    ]
