# Generated by Django 4.2.6 on 2026-01-28 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hep", "0021_alter_hepworkflow_workflow_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepdecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("exact_match", "await_decision_exact_match"),
                    ("fuzzy_match", "await_decision_fuzzy_match"),
                    (
                        "hep_accept",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "hep_accept_core",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "hep_reject",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "core_selection_accept",
                        "core_selection.await_decision_core_selection_approval",
                    ),
                    (
                        "core_selection_accept_core",
                        "core_selection.await_decision_core_selection_approval",
                    ),
                    ("auto_accept_core", ""),
                    ("auto_reject", ""),
                    (
                        "merge_approve",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_merge_conflicts_resolved",
                    ),
                    ("discard", ""),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hepdecision",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="email",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
    ]
