# Generated by Django 4.2.6 on 2026-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0021_alter_hepworkflow_workflow_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepdecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("exact_match", "await_decision_exact_match"),
                    ("fuzzy_match", "await_decision_fuzzy_match"),
                    (
                        "hep_accept",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "hep_accept_core",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "hep_reject",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "core_selection_accept",
                        "core_selection.await_decision_core_selection_approval",
                    ),
                    (
                        "core_selection_accept_core",
                        "core_selection.await_decision_core_selection_approval",
                    ),
                    ("auto_accept_core", ""),
                    ("auto_reject", ""),
                    (
                        "merge_approve",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_merge_conflicts_resolved",
                    ),
                    ("discard", ""),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hepworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("approval", "Waiting for approval"),
                    ("approval_core_selection", "Waiting for CORE selection approval"),
                    ("approval_fuzzy_matching", "Waiting for matching approval"),
                    ("approval_merge", "Waiting for merging conflicts"),
                    ("error", "Error"),
                    ("error_multiple_exact_matches", "Multiple exact matches"),
                    ("error_validation", "Validation error"),
                    ("running", "Running"),
                    ("blocked", "Blocked"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("missing_subject_fields", "Missing subject fields"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
    ]
