# Generated by Django 4.2.6 on 2026-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0022_alter_hepdecision_action_alter_hepworkflow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepdecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("exact_match", "await_decision_exact_match"),
                    ("fuzzy_match", "await_decision_fuzzy_match"),
                    (
                        "hep_accept",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "hep_accept_core",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "hep_reject",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "core_selection_accept",
                        "core_selection.await_decision_core_selection_approval",
                    ),
                    (
                        "core_selection_accept_core",
                        "core_selection.await_decision_core_selection_approval",
                    ),
                    ("auto_accept_core", ""),
                    ("auto_reject", ""),
                    (
                        "merge_approve",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_merge_conflicts_resolved",
                    ),
                    ("discard", ""),
                    (
                        "missing_subject_fields",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                ],
                max_length=30,
            ),
        ),
    ]
