# Generated by Django 4.2.6 on 2026-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0023_alter_hepdecision_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepdecision",
            name="value",
            field=models.TextField(blank=True, default=""),
        ),
    ]
