# Generated by Django 4.2.6 on 2026-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0024_alter_hepdecision_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("HEP_CREATE", "HEP create"),
                    ("HEP_PUBLISHER_CREATE", "HEP publisher create"),
                    ("HEP_PUBLISHER_UPDATE", "HEP publisher update"),
                    ("HEP_SUBMISSION", "HEP submission"),
                    ("HEP_UPDATE", "HEP update"),
                ],
                default="HEP_CREATE",
                max_length=30,
            ),
        ),
    ]
