# Generated by Django 4.2.6 on 2026-04-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0025_alter_hepworkflow_workflow_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hepworkflow",
            name="source_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
