# Generated by Django 4.2.6 on 2026-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0027_alter_hepdecision_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepdecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("exact_match", "await_decision_exact_match"),
                    ("fuzzy_match", "await_decision_fuzzy_match"),
                    (
                        "hep_accept",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "hep_accept_core",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "hep_reject",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "core_selection_accept",
                        "core_selection.await_decision_core_selection_approval",
                    ),
                    (
                        "core_selection_accept_core",
                        "core_selection.await_decision_core_selection_approval",
                    ),
                    ("auto_accept_core", ""),
                    ("auto_reject", ""),
                    (
                        "merge_approve",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_merge_conflicts_resolved",
                    ),
                    ("discard", ""),
                    (
                        "missing_subject_fields",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    ("withdrawn", ""),
                    ("manual_merge_approve", "await_merge_conflicts_resolved"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hepworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("HEP_CREATE", "HEP create"),
                    ("HEP_PUBLISHER_CREATE", "HEP publisher create"),
                    ("HEP_PUBLISHER_UPDATE", "HEP publisher update"),
                    ("HEP_SUBMISSION", "HEP submission"),
                    ("HEP_UPDATE", "HEP update"),
                    ("HEP_MANUAL_MERGE", "HEP manual merge"),
                ],
                default="HEP_CREATE",
                max_length=30,
            ),
        ),
    ]
