# Generated by Django 4.2.6 on 2026-08-03

from django.db import migrations, models

EXCLUSIVE_RESOLUTIONS = (
    "hep_accept",
    "hep_accept_core",
    "hep_reject",
    "core_selection_accept",
    "core_selection_accept_core",
)


def deduplicate_decisions(apps, schema_editor):
    HepDecision = apps.get_model("hep", "HepDecision")

    seen_workflows = set()
    duplicate_resolution_ids = []
    decisions = (
        HepDecision.objects.filter(action__in=EXCLUSIVE_RESOLUTIONS)
        .order_by("_created_at", "pk")
        .values("pk", "workflow_id")
    )
    for decision in decisions.iterator():
        if decision["workflow_id"] in seen_workflows:
            duplicate_resolution_ids.append(decision["pk"])
        else:
            seen_workflows.add(decision["workflow_id"])

    HepDecision.objects.filter(pk__in=duplicate_resolution_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0028_alter_hepdecision_action_and_more"),
    ]

    operations = [
        migrations.RunPython(deduplicate_decisions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="hepdecision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("action__in", EXCLUSIVE_RESOLUTIONS)),
                fields=("workflow",),
                name="unique_hep_resolution_per_workflow",
            ),
        ),
    ]
