# Generated by Django 4.2.6 on 2026-08-18

from django.db import migrations, models


def deduplicate_decisions(apps, schema_editor):
    HepDecision = apps.get_model("hep", "HepDecision")

    seen_decisions = set()
    duplicate_decision_ids = []
    decisions = HepDecision.objects.order_by("_created_at", "pk").values(
        "pk", "workflow_id", "action"
    )
    for decision in decisions.iterator():
        decision_key = (decision["workflow_id"], decision["action"])
        if decision_key in seen_decisions:
            duplicate_decision_ids.append(decision["pk"])
        else:
            seen_decisions.add(decision_key)

    HepDecision.objects.filter(pk__in=duplicate_decision_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0029_hepdecision_unique_hep_resolution_per_workflow"),
    ]

    operations = [
        migrations.RunPython(deduplicate_decisions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="hepdecision",
            constraint=models.UniqueConstraint(
                fields=("workflow", "action"),
                name="unique_hep_decision_per_workflow_and_action",
            ),
        ),
    ]
