# Generated by Django 5.2.17 on 2026-10-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0030_hepdecision_unique_per_workflow_and_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hepdecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("exact_match", "await_decision_exact_match"),
                    ("fuzzy_match", "await_decision_fuzzy_match"),
                    (
                        "hep_accept",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "hep_accept_core",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "hep_reject",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    (
                        "core_selection_accept",
                        "core_selection.await_decision_core_selection_approval",
                    ),
                    (
                        "core_selection_accept_core",
                        "core_selection.await_decision_core_selection_approval",
                    ),
                    ("auto_accept_core", ""),
                    ("auto_reject", ""),
                    (
                        "merge_approve",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_merge_conflicts_resolved",
                    ),
                    ("discard", ""),
                    ("purged", ""),
                    (
                        "missing_subject_fields",
                        "halt_for_approval_if_new_or_reject_if_not_relevant.await_decision_approval",
                    ),
                    ("withdrawn", ""),
                    ("manual_merge_approve", "await_merge_conflicts_resolved"),
                ],
                max_length=30,
            ),
        ),
    ]
