version: '2.1'

services:
  cypress:
    image: cypress/included:4.0.2
    volumes:
      - ./e2e:/tests
    environment:
      - NODE_ENV=test
      - CI=${CI}
    entrypoint: [""]
    depends_on:
      - ui
      - record-editor
  hep-web:
    build:
      context: backend
      dockerfile: Dockerfile-local
  hep-worker:
    build:
      context: backend
      dockerfile: Dockerfile-local
