version: '2.1'

services:
  cypress:
    image: cypress/included:13.0.0
    volumes:
      - ./e2e:/tests
    environment:
      - NODE_ENV=test
      - CI=${CI}
    entrypoint: ['']
    depends_on:
      - ui
      - record-editor
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./ui/docker/nginx/config/e2e.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hep-web
      - next-web
  hep-web:
    build:
      context: backend
      dockerfile: Dockerfile-local
  hep-worker:
    build:
      context: backend
      dockerfile: Dockerfile-local
