version: '2.1'

services:
  cypress:
    image: cypress/browsers:node13.6.0-chrome-80-ff72
    volumes:
      - ./e2e:/tests
    environment:
      - NODE_ENV=test
      - CI=${CI}
    entrypoint: ['']
    depends_on:
      - ui
      - record-editor
  hep-web:
    build:
      context: backend
      dockerfile: Dockerfile-local
  hep-worker:
    build:
      context: backend
      dockerfile: Dockerfile-local
