LITERATURE_PID_TYPE = "literature"
JOURNALS_PID_TYPE = "journals"

AFFILIATIONS_TO_HIDDEN_COLLECTIONS_MAPPING = {
    "IN2P3": "HAL Hidden",
    "CPPM": "HAL Hidden",
    "GANIL": "HAL Hidden",
    "IJCLAB": "HAL Hidden",
    "IP2I": "HAL Hidden",
    "IPHC": "HAL Hidden",
    "L2IT": "HAL Hidden",
    "LNCA": "HAL Hidden",
    "LP2I": "HAL Hidden",
    "LPNHE": "HAL Hidden",
    "LPSC": "HAL Hidden",
    "LUPM": "HAL Hidden",
    "SUBATECH": "HAL Hidden",
    "BINETRUY": "HAL Hidden",
    "BINÉTRUY": "HAL Hidden",
    "ILANCE": "HAL Hidden",
    "DMLAB": "HAL Hidden",
    "RINGUET": "HAL Hidden",
    "YUASA": "HAL Hidden",
    "AICP": "HAL Hidden",
    "MODANE": "HAL Hidden",
    "LPCA": "HAL Hidden",
    "INFINIS": "HAL Hidden",
    "IRENE JOLIOT": "HAL Hidden",
    "IRÈNE JOLIOT": "HAL Hidden",
    "IONS LOURDS": "HAL Hidden",
    "ASTROPARTICULE ET COSMOLOGIE": "HAL Hidden",
    "UNIVERS ET PARTICULES": "HAL Hidden",
    "PLURIDISCIPLINAIRE HUBERT CURIEN": "HAL Hidden",
    "CERN": "CDS Hidden",
    "FERMILAB": "Fermilab",
}
