FROM nginx:stable

EXPOSE 8081
CMD ["nginx", "-g", "daemon off;"]
ARG CACHE_DATE=not_a_date

ENV REACT_APP_SENTRY_DSN=https://8d6824a9531c437fbb6de2b3062dfa94@sentry.inspirehep.net/9 \
    REACT_APP_PIWIK_URL=//piwik.web.cern.ch \
    REACT_APP_PIWIK_SITE_ID=5664

WORKDIR /tmp

RUN apt-get update \
 && apt-get install -y curl gnupg2 \ 
 && curl -sLo node_setup https://deb.nodesource.com/setup_8.x \
 && bash node_setup \
 && apt-get update \
 && apt-get install --no-install-recommends -y nodejs \
 && npm install -g yarn \
 && rm -rf /var/lib/apt/lists/ 

COPY . /app/

WORKDIR /app

COPY docker/conf.d /etc/nginx/conf.d

RUN yarn install \
 && yarn run build \
 && chmod g+rwx /var/cache/nginx /var/run /var/log/nginx /usr/share/nginx \
 && sed -i.bak 's/^user/#user/' /etc/nginx/nginx.conf \
 && cp -r build/* /usr/share/nginx/html
