# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.settings.test --reuse-db"
python_files = [
    "tests.py",
    "test_*.py",
]

# ==== Coverage ====
[tool.coverage.run]
include = ["backoffice/**"]
omit = ["*/migrations/*", "*/tests/*"]
plugins = ["django_coverage_plugin"]



[tool.ruff]
extend-exclude = ["**/migrations/*.py"]


# ==== isort ====
[tool.ruff.lint.isort]
known-first-party = [
    "backoffice",
    "config",
]

[tool.poetry]
name = "backoffice"
version = "0.1.0"
description = ""
authors = ["inspire <admin@inspirehep.net.com>"]

[tool.poetry.dependencies]
python = "~3.11"
argon2-cffi = "25.1.0"
redis = "^8.1.0"
hiredis = "3.4.2"
celery = "5.6.3"
django-celery-beat = "2.9.0"
django = "^5.2.0"
django-environ = "0.14.0"
django-crispy-forms = "2.7"
crispy-bootstrap5 = "2026.9"
django-redis = "^6.0.0"
djangorestframework = "3.18.1"
django-cors-headers = "4.9.0"
drf-spectacular = "0.30.0"
psycopg = {version = "3.3.6", extras = ["c"]}
gunicorn = "26.2.0"
django-storages = {version = "1.14.6", extras = ["s3"]}
django-anymail = "15.2"
dj-database-url = "^3.1.2"
whitenoise = "^6.7.0"
django-prometheus = "^2.3.1"
django-opensearch-dsl = "^0.8.0"
django-elasticsearch-dsl-drf = {git = "https://github.com/cern-sis/django-elasticsearch-dsl-drf.git", rev = "opensearch"}
opensearch-dsl = "^2.1.0"
opensearch-py = "3.2.0"
djangorestframework-simplejwt = "^5.3.1"
django-json-widget = "^2.0.1"
sentry-sdk = "^2.60.0"
django-allauth = {version = "65.0.1", extras = ["headless"]}
inspire-schemas = "^61.6.33"
inspire-utils = "^3.0.70"

[tool.poetry.group.dev.dependencies]
factory-boy = "3.3.3"
pytest = "9.1.1"
pytest-sugar = "1.1.1"
coverage = "7.16.1"
pre-commit = "4.6.2"
django-debug-toolbar = "4.2.0"
django-extensions = "3.2.3"
django-coverage-plugin = "3.1.0"
pytest-django = "4.14.0"
pytest-vcr = "^1.0.2"
vcrpy = "^8.3.0"
parameterized = "^0.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
