# Generated by Django 4.2.6 on 2024-11-27 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("approval", "Waiting for approval"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="processing",
                        max_length=30,
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("HEP_CREATE", "HEP create"),
                            ("HEP_UPDATE", "HEP update"),
                            ("AUTHOR_CREATE", "Author create"),
                            ("AUTHOR_UPDATE", "Author update"),
                            ("DATA_CREATE", "Data create"),
                            ("DATA_UPDATE", "Data update"),
                        ],
                        default="HEP_CREATE",
                        max_length=30,
                    ),
                ),
                ("_created_at", models.DateTimeField(auto_now_add=True)),
                ("_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
