#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add lecacy_records_mirror table"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5ce9ef759ace"
down_revision = "b646d3592dd5"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_records_mirror",
        sa.Column("recid", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("marcxml", sa.LargeBinary(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=True),
        sa.Column("errors", sa.Text(), nullable=True),
        sa.Column("collection", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("recid", name=op.f("pk_legacy_records_mirror")),
    )
    op.create_index(
        op.f("ix_legacy_records_mirror_last_updated"),
        "legacy_records_mirror",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_legacy_records_mirror_valid_collection",
        "legacy_records_mirror",
        ["valid", "collection"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_legacy_records_mirror_valid_collection", table_name="legacy_records_mirror"
    )
    op.drop_index(
        op.f("ix_legacy_records_mirror_last_updated"),
        table_name="legacy_records_mirror",
    )
    op.drop_table("legacy_records_mirror")
    # ### end Alembic commands ###
