#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add index to pid_provider in pidstore"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "dc1ae5abe9d6"
down_revision = "c6570e49b7b2"
branch_labels = ()
depends_on = ("999c62899c20",)


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_pid_provider", "pidstore_pid", ["object_uuid", "pid_provider"])
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_pid_provider", table_name="pidstore_pid")
    # ### end Alembic commands ###
