import getValue from '../getValue';
import {
  RANK_VALUE_TO_DISPLAY,
  DEGREE_TYPE_TO_DISPLAY,
} from '../../../common/constants';

export const arxivCategoryOptions = [
  { value: 'astro-ph' },
  { value: 'cond-mat' },
  { value: 'cs' },
  { value: 'econ' },
  { value: 'eess' },
  { value: 'gr-qc' },
  { value: 'hep-ex' },
  { value: 'hep-lat' },
  { value: 'hep-ph' },
  { value: 'hep-th' },
  { value: 'math' },
  { value: 'math-ph' },
  { value: 'nlin' },
  { value: 'nucl-ex' },
  { value: 'nucl-th' },
  { value: 'physics' },
  { value: 'physics.acc-ph' },
  { value: 'physics.ins-det' },
  { value: 'q-bio' },
  { value: 'q-fin' },
  { value: 'quant-ph' },
  { value: 'stat' },
];
const otherSchemaArxivCategoryValues = [
  'astro-ph.CO',
  'astro-ph.EP',
  'astro-ph.GA',
  'astro-ph.HE',
  'astro-ph.IM',
  'astro-ph.SR',
  'cond-mat.dis-nn',
  'cond-mat.mes-hall',
  'cond-mat.mtrl-sci',
  'cond-mat.other',
  'cond-mat.quant-gas',
  'cond-mat.soft',
  'cond-mat.stat-mech',
  'cond-mat.str-el',
  'cond-mat.supr-con',
  'cs.AI',
  'cs.AR',
  'cs.CC',
  'cs.CE',
  'cs.CG',
  'cs.CL',
  'cs.CR',
  'cs.CV',
  'cs.CY',
  'cs.DB',
  'cs.DC',
  'cs.DL',
  'cs.DM',
  'cs.DS',
  'cs.ET',
  'cs.FL',
  'cs.GL',
  'cs.GR',
  'cs.GT',
  'cs.HC',
  'cs.IR',
  'cs.IT',
  'cs.LG',
  'cs.LO',
  'cs.MA',
  'cs.MM',
  'cs.MS',
  'cs.NA',
  'cs.NE',
  'cs.NI',
  'cs.OH',
  'cs.OS',
  'cs.PF',
  'cs.PL',
  'cs.RO',
  'cs.SC',
  'cs.SD',
  'cs.SE',
  'cs.SI',
  'cs.SY',
  'econ.EM',
  'econ.GN',
  'econ.TH',
  'eess.AS',
  'eess.IV',
  'eess.SP',
  'eess.SY',
  'math.AC',
  'math.AG',
  'math.AP',
  'math.AT',
  'math.CA',
  'math.CO',
  'math.CT',
  'math.CV',
  'math.DG',
  'math.DS',
  'math.FA',
  'math.GM',
  'math.GN',
  'math.GR',
  'math.GT',
  'math.HO',
  'math.IT',
  'math.KT',
  'math.LO',
  'math.MG',
  'math.MP',
  'math.NA',
  'math.NT',
  'math.OA',
  'math.OC',
  'math.PR',
  'math.QA',
  'math.RA',
  'math.RT',
  'math.SG',
  'math.SP',
  'math.ST',
  'nlin.AO',
  'nlin.CD',
  'nlin.CG',
  'nlin.PS',
  'nlin.SI',
  'physics.ao-ph',
  'physics.app-ph',
  'physics.atm-clus',
  'physics.atom-ph',
  'physics.bio-ph',
  'physics.chem-ph',
  'physics.class-ph',
  'physics.comp-ph',
  'physics.data-an',
  'physics.ed-ph',
  'physics.flu-dyn',
  'physics.gen-ph',
  'physics.geo-ph',
  'physics.hist-ph',
  'physics.med-ph',
  'physics.optics',
  'physics.plasm-ph',
  'physics.pop-ph',
  'physics.soc-ph',
  'physics.space-ph',
  'q-bio.BM',
  'q-bio.CB',
  'q-bio.GN',
  'q-bio.MN',
  'q-bio.NC',
  'q-bio.OT',
  'q-bio.PE',
  'q-bio.QM',
  'q-bio.SC',
  'q-bio.TO',
  'q-fin.CP',
  'q-fin.EC',
  'q-fin.GN',
  'q-fin.MF',
  'q-fin.PM',
  'q-fin.PR',
  'q-fin.RM',
  'q-fin.ST',
  'q-fin.TR',
  'stat.AP',
  'stat.CO',
  'stat.ME',
  'stat.ML',
  'stat.OT',
  'stat.TH',
];
export const arxivCategoryValues = arxivCategoryOptions
  .map(getValue)
  .concat(otherSchemaArxivCategoryValues);

export const inspireCategoryOptions = [
  { value: 'Accelerators' },
  { value: 'Astrophysics' },
  { value: 'Computing' },
  { value: 'Data Analysis and Statistics' },
  { value: 'Experiment-HEP' },
  { value: 'Experiment-Nucl' },
  { value: 'General Physics' },
  { value: 'Gravitation and Cosmology' },
  { value: 'Instrumentation' },
  { value: 'Lattice' },
  { value: 'Math and Math Physics' },
  { value: 'Other' },
  { value: 'Phenomenology-HEP' },
  { value: 'Theory-HEP' },
  { value: 'Theory-Nucl' },
];
export const inspireCategoryValues = inspireCategoryOptions.map(getValue);

export const rankOptions = Object.keys(RANK_VALUE_TO_DISPLAY).map(key => ({
  value: key,
  display: RANK_VALUE_TO_DISPLAY[key],
}));
export const rankValues = rankOptions.map(getValue);

export const degreeTypeOptions = Object.keys(DEGREE_TYPE_TO_DISPLAY).map(
  key => ({
    value: key,
    display: DEGREE_TYPE_TO_DISPLAY[key],
  })
);
export const degreeTypeValues = degreeTypeOptions.map(getValue);
