kind: pipeline
name: build
steps:
  - name: base
    image: inspirehep/drone-buildah:v0.1.0
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      destinations:
        - 'docker://docker.io/inspirehep/disambiguation:${DRONE_COMMIT_SHA}'
  - name: dev
    image: inspirehep/drone-buildah:v0.1.0
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.dev
      build_args:
        - FROM_TAG=${DRONE_COMMIT_SHA}
      destinations:
        - 'docker://docker.io/inspirehep/disambiguation:dev-${DRONE_COMMIT_SHA}'

---
kind: pipeline
name: test
clone:
  disable: true
depends_on:
  - build
steps:
  - name: flake8
    image: 'inspirehep/disambiguation:dev-${DRONE_COMMIT_SHA}'
    commands:
      - cd /opt/disambiguation
      - poetry run flake8
  - name: pytest
    image: 'inspirehep/disambiguation:dev-${DRONE_COMMIT_SHA}'
    commands:
      - cd /opt/disambiguation
      - poetry run py.test tests
