#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

set -e

# Clean redis
poetry run inspirehep shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
poetry run inspirehep db destroy --yes-i-know
poetry run inspirehep db init create
poetry run inspirehep index destroy --force --yes-i-know
poetry run inspirehep index init --force
poetry run inspirehep index queue init purge

# Create admin role to rectict access
poetry run inspirehep roles create admin
poetry run inspirehep access allow superuser-access role admin
poetry run inspirehep fixtures init
