# Generated by Django 4.2.6 on 2023-11-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0003_workflowticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("HEP_CREATE", "HEP create"),
                    ("HEP_UPDATE", "HEP update"),
                    ("AUTHOR_CREATE", "Author create"),
                    ("AUTHOR_UPDATE", "Author update"),
                ],
                default="HEP_create",
                max_length=30,
            ),
        ),
    ]
