# Generated by Django 4.2.6 on 2024-06-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0006_workflow__created_at_workflow__updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="core",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="is_update",
            field=models.BooleanField(default=False),
        ),
    ]
