# Generated by Django 4.2.6 on 2024-08-28 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0010_alter_decision_workflow_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflowticket",
            old_name="workflow_id",
            new_name="workflow",
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="_created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
