# Generated by Django 4.2.6 on 2024-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0011_rename_workflow_id_workflowticket_workflow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("approval", "Waiting for approva"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="queued",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("author_create_curation", "Author create curation"),
                    ("author_create_user", "Author create user"),
                    ("author_update_curation", "Author update curation"),
                ],
                default="author_create_curation",
                max_length=30,
            ),
        ),
    ]
