# Generated by Django 4.2.6 on 2024-06-03 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0005_workflowticket_ticket_type_alter_workflow_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="_created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflow",
            name="_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
