FROM node:16-alpine as development-stage

WORKDIR /usr/src/app

# Install system dependencies
RUN apk add --no-cache --virtual .build-deps \
    build-base \
    python3

COPY package*.json yarn.lock ./
RUN yarn install

COPY . .

# Remove system dependencies
RUN apk del .build-deps && yarn build

ARG VERSION
ENV REACT_APP_VERSION="${VERSION}"
ENV PATH /usr/src/app/node_modules/.bin:$PATH

EXPOSE 3000

CMD ["yarn", "start"]
