name: Backend build dependencies

on:
  push:
    branches: [master]
    paths:
      - 'backend/poetry.lock'
      - '.github/workflows/backend-integration.yml'
  pull_request:
    branches: [master]
    paths:
      - 'backend/poetry.lock'
      - '.github/workflows/backend-integration.yml'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: inspirehep/hep
          add_git_labels: true
          tags: deps-${{ hashFiles('backend/poetry.lock') }}
          path: backend/
          dockerfile: backend/Dockerfile-deps
          always_pull: true
