name: Pull request master

on:
  pull_request_target:
    branches: [master]


jobs:
  test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      search: ${{ contains(github.ref, 'opensearch') && 'opensearch' || 'elasticsearch' }}
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
