name: Pull request development (backend, ui & record-editor)

on:
  pull_request_target:
    branches: 'action-development-*'
    paths-ignore:
      - 'backoffice/**'
      - 'workflows/**'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
  test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
