name: Pull request master (workflows)

on:
  pull_request_target:
    branches: [master]
    paths:
      - "backoffice-repo/workflows/**"
      - "backoffice-repo/docker-compose.yaml"
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.ref }}
  test:
    needs: lint
    uses: ./.github/workflows/test-workflows.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
