name: Pull request development (workflows)

on:
  pull_request_target:
    branches: 'action-development-*'
    paths:
      - "workflows/**"
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
  test:
    needs: lint
    uses: ./.github/workflows/test-workflows.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
