name: Push main (backoffice)

on:
  workflow_call:

jobs:
  test:
    name: Tests (backoffice)
    uses: ./.github/workflows/test-backoffice.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
  deploy:
    name: Deploy (backoffice)
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: send event
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v6.3.1
        with:
          repo: cern-sis/kubernetes-inspire
          event-type: update
          images: |
            registry.cern.ch/cern-sis/inspire/backoffice@${{ needs.test.outputs.image-id }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
