name: Push main

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.ref }}
  backoffice:
    needs: lint
    uses: ./.github/workflows/push-main-backoffice.yml
    secrets: inherit
  workflows:
    needs: lint
    uses: ./.github/workflows/push-main-workflows.yml
    secrets: inherit
  success:
    name: All jobs passed
    runs-on: ubuntu-latest
    needs: [backoffice, workflows]
    steps:
      - name: All jobs passed
        run: echo "All jobs passed"
